sng/app_music/urls.py
from django.urls import path
from . import views



urlpatterns= [
    path('',views.home,name='home')

]

sng/sng/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('app_music.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sng/app_music/models.py
from django.db import models

# Create your models here.
class Artist(models.Model):
    fname= models.CharField(max_length=20,null = True, blank = True)
    lname= models.CharField(max_length=20,null = True, blank = True)
    nickname= models.CharField(max_length=20,null = True, blank = True)

    def save(self,*args,**kwargs):
        if self.fname or self.lname or self.nickname:
            super().save(*args,**kwargs)

    def __str__(self):
        if self.fname and self.lname:
            return self.fname +'  '+ self.lname
        elif self.fname:
            return self.fname
        elif self.lname:
            return lname
        elif self.nickname:
            return self.nickname

            
class Album(models.Model):
    artist = models.ForeignKey(Artist,on_delete=models.CASCADE, null = True)
    title = models.CharField(max_length=60,null = True)
    decription = models.TextField(null = True)
    summery = models.CharField(max_length=100,null = True)
    cover = models.ImageField(null=True, blank=False, upload_to='albums/%Y-%m-%d/')
    rate = models.FloatField(default = 0, null = True)
    release_date = models.DateField(null = True)
    like = models.PositiveSmallIntegerField(default=0, null= True)

    def __str__(self):
        return self.title


class Track(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE, null = True)
    title = models.CharField(max_length=20,null = True)
    music = models.FileField(upload_to='albums/%Y-%m-%d/')

    def __str__(self):
        return self.title


class Tag(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE, null = True)
    title = models.CharField(max_length=20,null=True)

sng/app_music/views.py
from django.shortcuts import render
from app_music.models import Album, Track
# Create your views here.
def home(request):
    #import ipdb; ipdb.set_trace()
    ctx ={}
    ctx['album'] = album = Album.objects.first()
    ctx['tracks'] = tracks = Track.objects.filter(album=album)
    ctx['tracks_count'] = len(tracks)
    return render(request,'home.html',ctx)

sng/app_music/templates/home.html
{% load costum_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <meta charset="utf-8">
<style media="screen">
@font-face {
    font-family: 'bnazanin';
    src: url('{% static 'Fonts/bnazanin.ttf' %} format("truetype")');
    }
body {font-family:'bnazanin'}
</style>
    </head>
    <body>
        <div class="row">
            <div class="col s8">
                <div class="card-panel">
                    <div class="center">{{album.summery}}</div>
                    <hr>
                    <div class="row">
                        <div class="col s4">
                            <img class="album-cover" src="{{album.cover.url}}"
                                    alt="{{album.title}}  {{album.summery}}"
                                    border-radius=5px height=230px>
                        </div>
                        <div class="col s8">
                            <h5 class="grey-text text-darken-3"><b>{{album.title}}</b></h5>
                            <div class="grey-text text-darken-1">by {{album.artist}}</div>
                            <div class="grey-text">released on {{album.release_date|date_splitter_1:'-'}}</div>
                            <div class="row">
                                <div class="col s1" style="margin-top: 10px">{{album.rate}}</div>
                                <div class="col s11">{{album.rate|starrate|safe}}</div>
                            </div>
                            <div class="row">
                                <div class="col s12">
                                    {% for tag in album.tag_set.all %}
                                        {{tag.title }}{% if not forloop.last %},{% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12">
                                {{ tracks_count }} track{%if tracks_count != 1%}s{%endif%}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col s4">
                <div class="card-panel"></div>
            </div>

        </div>

    </body>
</html>